spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/localdb;AUTO_SERVER=true
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      format_sql: true
    hibernate:
      ddl-auto: create

server:
  shutdown: graceful
